# Generated by Django 5.0.7 on 2024-08-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounting', '0002_consultingmodel_name_messagingmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultingmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='messagingmodel',
            name='user',
        ),
    ]
