# Generated by Django 5.0.7 on 2024-09-06 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounting', '0006_blogpost_alter_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='BlogPostModel',
        ),
    ]
